import logging
from typing import Optional
from app.schemas.decision_explanation import DecisionExplanation, PresentationOutput

logger = logging.getLogger("core-api.services.decision_presentation")

class DecisionPresentationService:
    """Stateless transformation service converting DecisionExplanation DTOs to presentation layers."""

    @staticmethod
    def build_metadata_section(explanation: DecisionExplanation) -> str:
        meta = explanation.metadata
        scenario_line = f"* **Scenario ID:** {meta.scenario_id}\n" if meta.scenario_id else ""
        trigger_line = ""
        if meta.trigger_event:
            evt = meta.trigger_event
            trigger_line = f"* **Trigger Event:** {evt.event_type} (Priority: {evt.priority or 'N/A'}, ID: {evt.event_id or 'N/A'})\n"
        
        return (
            f"# OptiFlow Decision Report\n"
            f"* **Decision ID:** {meta.decision_id}\n"
            f"* **Run ID:** {meta.run_id}\n"
            f"{scenario_line}"
            f"* **Timeline Position:** Stage {meta.timeline_position}\n"
            f"{trigger_line}"
            f"* **Timestamp:** {meta.timestamp}\n"
            f"* **Generated By:** Decision Intelligence Presentation Layer\n"
            f"* **Version:** 1.0\n"
        )

    @staticmethod
    def build_executive_summary_section(explanation: DecisionExplanation) -> str:
        es = explanation.executive_summary
        return (
            f"## Executive Summary\n"
            f"**{es.headline}**\n\n"
            f"{es.summary_text}\n"
        )

    @staticmethod
    def build_reasoning_section(explanation: DecisionExplanation) -> str:
        reasoning = explanation.reasoning
        
        reasons_list = "\n".join(f"- {r}" for r in reasoning.reasons)
        
        # Evidence check-list formatting
        ev = reasoning.evidence_used
        crm_lines = "\n".join(f"  - ✓ {item}" for item in ev.crm) if ev.crm else "  - *No CRM details referenced*"
        inc_lines = "\n".join(f"  - ✓ {item}" for item in ev.incident) if ev.incident else "  - *No Incident details referenced*"
        work_lines = "\n".join(f"  - ✓ {item}" for item in ev.workforce) if ev.workforce else "  - *No Workforce details referenced*"
        opt_lines = "\n".join(f"  - ✓ {item}" for item in ev.optimizer) if ev.optimizer else "  - *No Optimizer details referenced*"
        
        # Reasoning path flow
        path_flow = " ➔ ".join(step.step_name for step in reasoning.reasoning_path)
        
        return (
            f"## Decision Justification\n"
            f"### Reasons\n"
            f"{reasons_list}\n\n"
            f"### Evidence Used\n"
            f"* **CRM Evidence:**\n{crm_lines}\n"
            f"* **Incident Evidence:**\n{inc_lines}\n"
            f"* **Workforce Evidence:**\n{work_lines}\n"
            f"* **Optimizer Evidence:**\n{opt_lines}\n\n"
            f"### AI Reasoning Trace\n"
            f"`{path_flow}`\n"
        )

    @staticmethod
    def build_alternative_plans_section(explanation: DecisionExplanation) -> str:
        rec = explanation.recommendation
        
        # Format Selected Profile
        selected_block = (
            f"### Recommended Profile Strategy: {rec.selected_profile}\n"
            f"> [!IMPORTANT]\n"
            f"> **Justification:** {rec.selection_reason}\n"
        )
        
        # Format Alternatives Table
        if not rec.alternatives:
            alternatives_table = "*No alternative candidate strategies recorded.*"
        else:
            table_header = (
                f"| Rank | Profile Strategy | Objective | SLA | Revenue | Fairness | Workload | Rejection Reason |\n"
                f"| :---: | :--- | :---: | :---: | :---: | :---: | :---: | :--- |\n"
            )
            table_rows = []
            for alt in rec.alternatives:
                table_rows.append(
                    f"| #{alt.rank} | {alt.profile} | {alt.objective_score:.1f} | {alt.sla_score:.1f}% | "
                    f"{alt.revenue_score:.1f}% | {alt.fairness_score:.1f}% | {alt.workload_score:.1f}% | "
                    f"{alt.selection_or_rejection_reason} |"
                )
            alternatives_table = table_header + "\n".join(table_rows)
            
        return (
            f"## Candidate Strategy Comparison\n"
            f"{selected_block}\n"
            f"### Alternative Strategy Evaluations\n"
            f"{alternatives_table}\n"
        )

    @staticmethod
    def build_business_impact_section(explanation: DecisionExplanation) -> str:
        impact = explanation.business_impact
        
        # KPIs List
        kpis_lines = []
        for k in impact.kpis:
            kpis_lines.append(f"- **{k.metric_name}:** {k.display_value} ({k.impact_level})")
        kpis_block = "\n".join(kpis_lines) if kpis_lines else "- *No business KPIs compiled*"
        
        # Tradeoffs lists
        benefits_str = "\n".join(f"  - ✓ {b}" for b in impact.tradeoffs.benefits) if impact.tradeoffs.benefits else "  - *No specific positive benefits highlighted*"
        drawbacks_str = "\n".join(f"  - ⚠ {d}" for d in impact.tradeoffs.drawbacks) if impact.tradeoffs.drawbacks else "  - *No negative tradeoffs flagged*"
        
        return (
            f"## Expected Business Impact\n"
            f"### Key Metrics & KPIs\n"
            f"{kpis_block}\n\n"
            f"### Strategy Trade-offs\n"
            f"* **Benefits:**\n{benefits_str}\n"
            f"* **Drawbacks (Mitigation required):**\n{drawbacks_str}\n"
        )

    @staticmethod
    def build_operational_actions_section(explanation: DecisionExplanation) -> str:
        actions = explanation.actions
        if not actions:
            return "## Recommended Actions\n*No explicit actions resolved.*"
            
        action_rows = []
        for a in actions:
            action_rows.append(f"- [ ] **[{a.priority}]** {a.action_text} (Assignee: {a.assignee}, Effect: {a.expected_effect})")
            
        return (
            f"## Recommended Actions\n"
            + "\n".join(action_rows) + "\n"
        )

    @staticmethod
    def build_confidence_section(explanation: DecisionExplanation) -> str:
        conf = explanation.recommendation.confidence
        return (
            f"## AI Confidence Assessment\n"
            f"* **Confidence Level:** {conf.level} ({conf.score:.1f}%)\n"
            f"* **Confidence Rationale:** {conf.reason}\n"
        )

    @staticmethod
    def build_decision_outcome_section(explanation: DecisionExplanation) -> str:
        out = explanation.outcome
        notes = f"\n* **Evaluation Notes:** {out.evaluation_notes}" if out.evaluation_notes else ""
        return (
            f"## Post-Execution Audit Evaluation\n"
            f"* **Execution Status:** {out.status}\n"
            f"* **Observed Business Impact:** {out.observed_impact or 'Awaiting observations...'}"
            f"{notes}\n"
        )

    @classmethod
    def to_business_summary(cls, explanation: DecisionExplanation) -> str:
        """Converts the DTO into a concise executive-focused Markdown summary block."""
        es = explanation.executive_summary
        reasons_str = "\n".join(f"- {r}" for r in explanation.reasoning.reasons[:3])
        if len(explanation.reasoning.reasons) > 3:
            reasons_str += "\n- *Additional operational reasons analyzed*"
            
        return (
            f"### {es.headline}\n"
            f"{es.summary_text}\n\n"
            f"**Core Justification Reasons:**\n"
            f"{reasons_str}"
        )

    @classmethod
    def to_change_summary(cls, explanation: DecisionExplanation) -> str:
        """Converts the DTO into a detailed, structured audit scorecard document."""
        # Combines reasoning details, candidate alternatives tables, and actions lists
        reasoning = cls.build_reasoning_section(explanation)
        alts = cls.build_alternative_plans_section(explanation)
        impact = cls.build_business_impact_section(explanation)
        actions = cls.build_operational_actions_section(explanation)
        
        return (
            f"# Strategy Decision Audit Scorecard\n\n"
            f"{reasoning}\n"
            f"{alts}\n"
            f"{impact}\n"
            f"{actions}"
        )

    @classmethod
    def to_markdown_report(cls, explanation: DecisionExplanation) -> str:
        """Assembles all structured sections into a single complete printable document report."""
        return "\n".join([
            cls.build_metadata_section(explanation),
            cls.build_executive_summary_section(explanation),
            cls.build_reasoning_section(explanation),
            cls.build_alternative_plans_section(explanation),
            cls.build_business_impact_section(explanation),
            cls.build_operational_actions_section(explanation),
            cls.build_confidence_section(explanation),
            cls.build_decision_outcome_section(explanation)
        ])

    @classmethod
    def generate_presentation(cls, explanation: DecisionExplanation) -> PresentationOutput:
        """Helper assembling all three string representations inside a typed PresentationOutput container."""
        return PresentationOutput(
            business_summary=cls.to_business_summary(explanation),
            change_summary=cls.to_change_summary(explanation),
            markdown_report=cls.to_markdown_report(explanation)
        )
