from enum import StrEnum

class FreshnessStatus(StrEnum):
    FRESH = "FRESH"
    STALE_ALLOWED = "STALE_ALLOWED"
    STALE_BLOCKING = "STALE_BLOCKING"
    MISSING = "MISSING"
    CONFLICTING = "CONFLICTING"
    INVALID = "INVALID"

class FailureMode(StrEnum):
    NONE = "NONE"
    TIMEOUT = "TIMEOUT"
    HTTP_500 = "HTTP_500"
    MALFORMED_RESPONSE = "MALFORMED_RESPONSE"
    EMPTY_RESPONSE = "EMPTY_RESPONSE"

class EscalationStatus(StrEnum):
    OPEN = "OPEN"
    ASSIGNED = "ASSIGNED"
    IN_PROGRESS = "IN_PROGRESS"
    MONITORING = "MONITORING"
    RESOLVED = "RESOLVED"

class AssignmentRequestStatus(StrEnum):
    PENDING = "PENDING"
    ACCEPTED = "ACCEPTED"
    REJECTED = "REJECTED"
    EXPIRED = "EXPIRED"

class ToolService(StrEnum):
    CRM = "crm-service"
    INCIDENT = "incident-service"
    WORKFORCE = "workforce-service"
    COMMUNICATION = "communication-service"

class EvidenceImportance(StrEnum):
    REQUIRED = "REQUIRED"
    OPTIONAL = "OPTIONAL"
    DECISION_CRITICAL = "DECISION_CRITICAL"

class ObjectiveType(StrEnum):
    SLA_PROTECTION = "SLA_PROTECTION"
    COMMERCIAL_PROTECTION = "COMMERCIAL_PROTECTION"
    RENEWAL_PROTECTION = "RENEWAL_PROTECTION"
    CUSTOMER_FAIRNESS = "CUSTOMER_FAIRNESS"
    WORKLOAD_PROTECTION = "WORKLOAD_PROTECTION"
    MINIMISE_CONTEXT_SWITCHING = "MINIMISE_CONTEXT_SWITCHING"

class EvidenceType(StrEnum):
    CUSTOMER_IDENTITY = "CUSTOMER_IDENTITY"
    CUSTOMER_ARR = "CUSTOMER_ARR"
    CUSTOMER_TIER = "CUSTOMER_TIER"
    RENEWAL_DATE = "RENEWAL_DATE"
    COMMERCIAL_DEPENDENCIES = "COMMERCIAL_DEPENDENCIES"
    RELATIONSHIP_CONTEXT = "RELATIONSHIP_CONTEXT"
    
    ACTIVE_ESCALATIONS = "ACTIVE_ESCALATIONS"
    SLA_DEADLINES = "SLA_DEADLINES"
    SEVERITY = "SEVERITY"
    WORKAROUND_STATUS = "WORKAROUND_STATUS"
    REQUIRED_SKILLS = "REQUIRED_SKILLS"
    REQUIRED_ACCESS = "REQUIRED_ACCESS"
    CURRENT_ASSIGNMENT = "CURRENT_ASSIGNMENT"
    POSTPONEMENT_HISTORY = "POSTPONEMENT_HISTORY"
    WAITING_TIME = "WAITING_TIME"
    
    SPECIALIST_SKILLS = "SPECIALIST_SKILLS"
    SPECIALIST_ACCESS = "SPECIALIST_ACCESS"
    SPECIALIST_AVAILABILITY = "SPECIALIST_AVAILABILITY"
    SPECIALIST_CAPACITY = "SPECIALIST_CAPACITY"
    CURRENT_WORKLOAD = "CURRENT_WORKLOAD"
    AFTER_HOURS_MINUTES = "AFTER_HOURS_MINUTES"
    OVERNIGHT_INCIDENT_COUNT = "OVERNIGHT_INCIDENT_COUNT"
    RECENT_INTERRUPTION_COUNT = "RECENT_INTERRUPTION_COUNT"
    
    ASSIGNMENT_RESPONSE = "ASSIGNMENT_RESPONSE"
    NOTIFICATION_STATUS = "NOTIFICATION_STATUS"
