# Stable IDs for the Phase 2 demonstration dataset

# Customers
CUSTOMER_ALPHA = "CUS-ALPHA"
CUSTOMER_NOVA = "CUS-NOVA"
CUSTOMER_GREEN = "CUS-GREEN"
CUSTOMER_MEDI = "CUS-MEDI"

ALL_CUSTOMERS = {CUSTOMER_ALPHA, CUSTOMER_NOVA, CUSTOMER_GREEN, CUSTOMER_MEDI}

# Escalations
ESCALATION_ALPHA = "ESC-ALPHA-01"
ESCALATION_NOVA = "ESC-NOVA-01"
ESCALATION_GREEN = "ESC-GREEN-01"
ESCALATION_MEDI = "ESC-MEDI-01"

# Specialists
SPECIALIST_MAYA = "SP-MAYA"
SPECIALIST_DANIEL = "SP-DANIEL"
SPECIALIST_NIMAL = "SP-NIMAL"
